/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

//#define HAVE_CHAMELIUM 1

#define HAVE_CPUID_H 1

#define HAVE_GETTID 1

#define HAVE_LIBDRM_NOUVEAU 1

#define HAVE_LIBGEN_H 1

#define HAVE_LINUX_KD_H 1

#define HAVE_MEMFD_CREATE 1

#define HAVE_STRUCT_SYSINFO_TOTALRAM 1

#define HAVE_SYS_IO_H 1

#define HAVE_SYS_KD_H 1

// #define HAVE_VALGRIND 1

#define PACKAGE "igt-gpu-tools"

#define PACKAGE_NAME igt-gpu-tools

#define PACKAGE_STRING igt-gpu-tools 1.26

#define PACKAGE_VERSION "1.26"

//#define TARGET_CPU_PLATFORM "x86_64"

